warmup4: hw4_provided.h  hw4_provided.c warmup4.c  warmup4_main.c
	clang -Wall -lpng hw4_provided.c \
	warmup4.c warmup4_main.c -o warmup4

hw4: hw4.h hw4.c hw4_main.c hw4_provided.c hw4_provided.h
	clang -Wall -lpng -o hw4 hw4.c hw4_main.c hw4_provided.c
